### ISSUE TITLE
Change the order in the manifest

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/bridge-marker#7] opened 2019-04-25 09:54 UTC
I take a look on the std-ci logs and found that it takes time for the service account to exist.

```
daemonset.extensions/bridge-marker created
clusterrole.rbac.authorization.k8s.io/bridge-marker-cr created
clusterrolebinding.rbac.authorization.k8s.io/bridge-marker-crb created
serviceaccount/bridge-marker created
+ timeout=300
+ sample=30
+ current_time=0
+ true
++ kubectl describe daemonset bridge-marker -n kube-system
++ cluster/kubectl.sh describe daemonset bridge-marker -n kube-system
+ describe_result='Name:           bridge-marker
Selector:       app=bridge-marker,tier=node
Node-Selector:  beta.kubernetes.io/arch=amd64
Labels:         app=bridge-marker
                tier=node
Annotations:    <none>
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=bridge-marker
                    tier=node
  Service Account:  bridge-marker
  Containers:
   bridge-marker:
    Image:      quay.io/kubevirt/bridge-marker:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      -node-name
      $(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason        Age   From                  Message
  ----     ------        ----  ----                  -------
  Warning  FailedCreate  1s    daemonset-controller  Error creating: pods "bridge-marker-" is forbidden: error looking up service account kube-system/bridge-marker: serviceaccount "bridge-marker" not found'
++ echo 'Name:           bridge-marker
Selector:       app=bridge-marker,tier=node
Node-Selector:  beta.kubernetes.io/arch=amd64
Labels:         app=bridge-marker
                tier=node
Annotations:    <none>
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=bridge-marker
                    tier=node
  Service Account:  bridge-marker
  Containers:
   bridge-marker:
    Image:      quay.io/kubevirt/bridge-marker:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      -node-name
      $(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason        Age   From                  Message
  ----     ------        ----  ----                  -------
  Warning  FailedCreate  1s    daemonset-controller  Error creating: pods "bridge-marker-" is forbidden: error looking up service account kube-system/bridge-marker: serviceaccount "bridge-marker" not found'
++ grep 'Desired Number of Nodes Scheduled'
++ awk -F : '{print $2}'
+ desired_nodes=' 0'
++ echo 'Name:           bridge-marker
Selector:       app=bridge-marker,tier=node
Node-Selector:  beta.kubernetes.io/arch=amd64
Labels:         app=bridge-marker
                tier=node
Annotations:    <none>
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=bridge-marker
                    tier=node
  Service Account:  bridge-marker
  Containers:
   bridge-marker:
    Image:      quay.io/kubevirt/bridge-marker:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      -node-name
      $(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason        Age   From                  Message
  ----     ------        ----  ----                  -------
  Warning  FailedCreate  1s    daemonset-controller  Error creating: pods "bridge-marker-" is forbidden: error looking up service account kube-system/bridge-marker: serviceaccount "bridge-marker" not found'
++ grep 'Number of Nodes Scheduled with Up-to-date Pods'
++ awk -F : '{print $2}'
+ current_nodes=' 0'
+ '[' 0 -eq 0 ']'
+ break
```

I think if we move the daemonset to the end of the manifest file it will help.

**Comment by SchSeba** [comment] 2019-04-25 09:55
@mmirecki Can you take a look on this please?

**Comment by mmirecki** [comment] 2019-04-30 11:44
I'm unable to reproduce the issue. 
Tried the following commands multiple times on both k8s and os
    ./cluster/kubectl.sh delete -f examples/bridge-marker.yml
    ./cluster/kubectl.sh apply -f examples/bridge-marker.yml
    ./cluster/kubectl.sh describe ds -n kube-system bridge-marker
but have not see a failed event once.

With Sebastian's ack, I'm closing the issue.

**Comment by RamLavi** [comment] 2020-07-21 12:47
We also see this issue on [cnao](https://github.com/kubevirt/cluster-network-addons-operator), sometimes (~1 in 3 times) our ci tests fail because of this issue (there is an open [issue](https://github.com/kubevirt/cluster-network-addons-operator/issues/462) for flakyness).
@mmirecki can you please reopen the issue?

prow logs: 
[1] example [PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/456), where it currently fails.
[2] [upgrade_test](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/456/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1285532992155947008#1:build-log.txt%3A1950), when operator in version 0.27.0 is installed and supported spec configured and it is upgraded to the latest release it should report expected deployed container images and leave no leftovers from the previous version
[3] [upgrade test](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/456/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1285532992155947008#1:build-log.txt%3A3237), when operator in version 0.27.0 is installed and supported spec configured should transition reported versions while being upgraded to version 99.0.0

@qinqon FYI

**Comment by phoracek** [comment] 2020-07-21 17:26
It is an annoying issue but not a cause for our failure IIUIC. Even if we fail on the order, on the re-reconcile, we should apply all the manifests again and thus eventually get them all applied.

**Closed** 2020-12-18 18:06 UTC
Labels: lifecycle/rotten
